### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by lukepalmer** [lukepalmer/zeromq-native#3]
I'm going to give this a try, but if anyone out there is an appveyor expert your help would be most welcome.

**Comment by lukepalmer** [comment]
@zhivko want to give the latest snapshot a try?

**Comment by zhivko** [comment]
OK tried it and I get:

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError:
C:\Users\klemen\AppData\Local\Temp\libjzmq-8821477166054408565.lib: Can't
find dependent libraries
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
at java.lang.Runtime.load0(Runtime.java:809)
at java.lang.System.load(System.java:1086)
at
org.zeromq.EmbeddedLibraryTools.loadEmbeddedLibrary(EmbeddedLibraryTools.java:136)
at org.zeromq.EmbeddedLibraryTools.<clinit>(EmbeddedLibraryTools.java:22)
at org.zeromq.ZMQ.<clinit>(ZMQ.java:39)
at org.zeromq.ZContext.createSocket(ZContext.java:86)
...

I use libraries defining dependeny in my pom.xml like this:

<dependency> <groupId>net.lukepalmer</groupId>
<artifactId>zeromq-native</artifactId> <version>4.1.5-SNAPSHOT</version>
</dependency> 
<dependency> <groupId>org.zeromq</groupId> <artifactId>jzmq</artifactId>
<version>3.1.0</version> </dependency>

Shoud this be enough also to get all dependent libraries or I miss some
dependency?

**Comment by zhivko** [comment]
OK tried it and I get:

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: C:\Users\klemen\AppData\Local\Temp\libjzmq3476815834723789253.lib: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at org.zeromq.EmbeddedLibraryTools.loadEmbeddedLibrary(EmbeddedLibraryTools.java:148)
    at org.zeromq.EmbeddedLibraryTools.<clinit>(EmbeddedLibraryTools.java:17)
    at org.zeromq.ZMQ.<clinit>(ZMQ.java:40)
    at org.zeromq.ZContext.createSocket(ZContext.java:86)
...
```

I use libraries defining dependency in my pom.xml like this:

```
        <dependency>
            <groupId>net.lukepalmer</groupId>
            <artifactId>zeromq-native</artifactId>
            <version>4.1.5-SNAPSHOT</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.zeromq/jzmq -->
        <dependency>
            <groupId>net.lukepalmer</groupId>
            <artifactId>jzmq</artifactId>
            <version>3.1.1-SNAPSHOT</version>
        </dependency>
```

In my temp folder this files are created:
c:\Users\klemen\AppData\Local\Temp\libjzmq3476815834723789253.lib
c:\Users\klemen\AppData\Local\Temp\libzmq5721571919440605138.lib
c:\Users\klemen\AppData\Local\Temp\libsodium941840329795589108.lib

Exception is thrown when System.load(c:\Users\klemen\AppData\Local\Temp\libjzmq3476815834723789253.lib).

**Comment by zhivko** [comment]
Using dependency walker for libjzmq.lib it seems that:
LIBZMQ-V140-MT-4_2_0.DLL
is missing. Probably you should dispatch this dll also with others (libjzmq, libzmq, libsodium)?
After puting LIBZMQ-V140-MT-4_2_0.dll to the temp folder where EmbeddedLibraryTools is extracting natives, I dont get exception anymore.
LIBZMQ-V140-MT-4_2_0.dll is actually windows build of libzmq (https://github.com/zeromq/libzmq.git) , originally named as
\git\libzmq\bin\x64\Release\v140\dynamic\libzmq.dll

**Comment by lukepalmer** [comment]
Thanks for testing!

libzmq<xxxx>.dll just means libzmq.dll. Dependency walker doesn't know how
(or more accurately I don't know how) to examine what's missing across
multiple DLLs at once.

My best guess is that this is related to the Visual C++ runtime linkage in
the build, but this will take some work to find.

I may have some time late in a week or so, pull requests much appreciated
as well!

**Comment by lukepalmer** [comment]
I'd speculate that the packaged dll has something wrong with it, and the one you built does not. Now we just have to find the difference.

**Comment by zhivko** [comment]
Thing is that your libjzmq references libzmq-v140-mt-4_2_0.dll. So what I
did I took my dynamic build, rename it to needed dll name and that it
worked...
I am attaching picture (since I am replying through email I hope git will
accept it somehow).

**Comment by zhivko** [comment]
How did you did windows build libzmq.build? Through VisualStudio?

**Comment by zhivko** [comment]
Thing is that your libjzmq references libzmq-v140-mt-4_2_0.dll. So what I
did I took my dynamic build, rename it to needed dll name and that it
worked...
How did you did windows build libzmq.build? Through VisualStudio?
I am attaching picture below.
![dependency](https://cloud.githubusercontent.com/assets/3688966/18914737/a1555396-858e-11e6-8940-5a87b02f60e8.jpg)

**Comment by lukepalmer** [comment]
The build happens in [appveyor](../blob/master/appveyor.yml) so that it's public and repeatable. The picture you are showing looks like Visual C++ dependency issues, but dependency walker is a tricky beast. 

No time at the present but I'll come back to this.

**Comment by zhivko** [comment]
My build is with visualstudio 2015 comunity eddition opening:
git\libzmq\builds\msvc\vs2015\libzmq.sln
and then building in visual studio 2015.

**Comment by lukepalmer** [comment]
Right. We unfortunately do need to use headless / appveyor here. We're reasonably close though.

**Comment by zhivko** [comment]
Do you know maybe what could be steps to isolate issue? Should I post logs
of VS2015 build? WOuld that help?

**Comment by lukepalmer** [comment]
The steps I was planning to follow are
1. Add maven invocation to the appveyor script to (hopefully) reproduce the failure
2. Actually track down the missing linkage locally. Likely a tweak to cmake options will do it.

Build logs probably wouldn't add anything at this point but would very much appreciate help with the above.

**Comment by zhivko** [comment]
Beside of this - I am testing now with jzmq instead of JeroMQ and main difference beeing - I needed to change my prog to remove ZMQ.Charset in call socket.send(msg, ZMQ.Charset).
Now I have:
                        socket.send(new String(buff));
ofcourse
byte[] buff

But server that before nicely worked with JeroMQ library on client now complains that it cannot find some data...

```
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "pb.Container" because it is missing required fields: type
```

Is there any way how to specify ZMQ.Charset - if this is the only possible reason for error?

**Comment by lukepalmer** [comment]
That's probably a question better directed to a jzmq audience. For this
project, if the library loads then we're good.

**Comment by zhivko** [comment]
AH find this I needed to use:
                        socket.send(buff, 0);

**Comment by zhivko** [comment]
Now I builded through AppVeyor (I forked from libzmq) and my inside x64 release job artifact thereis libzmq-v140-mt-4_2_0.dll file that is 470016Bytes (slightly more than my local VS2015 build) and it has correct name (same as DependencyWalker shows)  - so I wonder now how you did AppVeyor build.
I copied it in temp folder near:
c:\Users\klemen\AppData\Local\Temp\libjzmq3646520560823379282.lib
c:\Users\klemen\AppData\Local\Temp\libzmq8140900927620979615.lib
c:\Users\klemen\AppData\Local\Temp\libsodium6108433792585586611.lib
and it works OK.

**Comment by lukepalmer** [comment]
I reproduced the failure in the appveyor build, now seen at HEAD. So that'll give us something to go on to actually fix this.

**Comment by zhivko** [comment]
"now seen at HEAD" meaning what - sorry I'm little bit out of git world :)

**Comment by zhivko** [comment]
Hi @lukepalmer could you give some feedback? Do you think that could be solved or at least move forward in reasonable time?

**Comment by lukepalmer** [comment]
I think there's one minor remaining issue with linkage in the last step.
This would probably be straightforward for someone who knows a lot about
Windows development (which I do not).

I was planning to look into this more over the next week or two, but a pull
request from a Windows expert would be even better.
